version: "2"
services:
    web:
        build: build/bts/.
        ports:
            - "4000:4000"
        volumes:
            - ./data:/bts/data
        restart: always
    hub:
        build: build/hub/.
        ports:
            - "3001:3001"
        restart: always
